/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author juancho
 */
public class VISUAL extends javax.swing.JFrame {

    /**
     * Creates new form VISUAL
     */
    public VISUAL() {
        initComponents();
        Buscarr.add(nombrer);
        Buscarr.add(caller);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscarr = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FECHA = new javax.swing.JLabel();
        ordenlbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ordentx = new javax.swing.JTextField();
        nombretx = new javax.swing.JTextField();
        equipotx = new javax.swing.JTextField();
        calletx = new javax.swing.JTextField();
        cruzatx = new javax.swing.JTextField();
        coloniatx = new javax.swing.JTextField();
        municipiotx = new javax.swing.JTextField();
        teltx = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        trabajotx = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        buscarbt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        borrarbt = new javax.swing.JButton();
        editarbt = new javax.swing.JButton();
        nuevobt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        atendidotx = new javax.swing.JTextField();
        cancelarbt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        nombrer = new javax.swing.JRadioButton();
        caller = new javax.swing.JRadioButton();
        borrarbtn = new javax.swing.JButton();
        fechatx = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 894));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                editar(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 187, 75, 22);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Tel:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(668, 195, 32, 22);

        jLabel3.setText("jLabel1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(443, 121, 45, 0);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Equipo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(730, 130, 65, 22);

        FECHA.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        FECHA.setText("Fecha:");
        getContentPane().add(FECHA);
        FECHA.setBounds(340, 130, 56, 22);

        ordenlbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ordenlbl.setText("Orden de visita:");
        getContentPane().add(ordenlbl);
        ordenlbl.setBounds(54, 132, 137, 22);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Calle y nº:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(54, 257, 88, 22);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("Colonia:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(54, 313, 71, 22);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Cruza con:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(551, 252, 93, 22);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("Municipio");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(621, 313, 84, 22);

        ordentx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(ordentx);
        ordentx.setBounds(203, 127, 130, 32);

        nombretx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nombretx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxActionPerformed(evt);
            }
        });
        getContentPane().add(nombretx);
        nombretx.setBounds(130, 187, 530, 32);

        equipotx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(equipotx);
        equipotx.setBounds(800, 130, 103, 32);

        calletx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        calletx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calletxActionPerformed(evt);
            }
        });
        getContentPane().add(calletx);
        calletx.setBounds(154, 252, 362, 32);

        cruzatx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(cruzatx);
        cruzatx.setBounds(656, 248, 186, 32);

        coloniatx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(coloniatx);
        coloniatx.setBounds(131, 308, 293, 32);

        municipiotx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(municipiotx);
        municipiotx.setBounds(711, 308, 160, 32);

        teltx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(teltx);
        teltx.setBounds(706, 190, 160, 32);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setText("Trabajo realizado:");

        trabajotx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(trabajotx);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(42, 504, 947, 350);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel11.setText("Historial:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 470, 72, 20);

        buscarbt.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        buscarbt.setText("Buscar");
        buscarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbtActionPerformed(evt);
            }
        });
        getContentPane().add(buscarbt);
        buscarbt.setBounds(40, 350, 100, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 60)); // NOI18N
        jLabel13.setText("CEROCONTAMINACION");

        jLabel5.setText("CHEQUEO DE CALENTADOR SOLAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel13)
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(384, 384, 384))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1007, 115);

        borrarbt.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        borrarbt.setText("Eliminar");
        borrarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbtActionPerformed(evt);
            }
        });
        getContentPane().add(borrarbt);
        borrarbt.setBounds(140, 390, 114, 30);

        editarbt.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        editarbt.setText("Editar");
        editarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarbtActionPerformed(evt);
            }
        });
        getContentPane().add(editarbt);
        editarbt.setBounds(240, 350, 94, 30);

        nuevobt.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nuevobt.setText("Nuevo");
        nuevobt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevobtActionPerformed(evt);
            }
        });
        getContentPane().add(nuevobt);
        nuevobt.setBounds(340, 350, 98, 30);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("Atendido por:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(580, 370, 119, 22);

        atendidotx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(atendidotx);
        atendidotx.setBounds(700, 370, 150, 32);

        cancelarbt.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cancelarbt.setText("Cancelar");
        cancelarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarbtActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarbt);
        cancelarbt.setBounds(440, 350, 118, 30);

        jButton1.setText("prueba");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(890, 250, 87, 29);

        nombrer.setText("Nombre");
        getContentPane().add(nombrer);
        nombrer.setBounds(10, 390, 82, 23);

        caller.setText("Calle");
        caller.setAutoscrolls(true);
        getContentPane().add(caller);
        caller.setBounds(10, 410, 63, 23);

        borrarbtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        borrarbtn.setText("Borrar");
        borrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbtnActionPerformed(evt);
            }
        });
        getContentPane().add(borrarbtn);
        borrarbtn.setBounds(140, 350, 96, 30);
        getContentPane().add(fechatx);
        fechatx.setBounds(405, 130, 280, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombretxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretxActionPerformed
       
    }//GEN-LAST:event_nombretxActionPerformed

    private void buscarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbtActionPerformed
        
        //base de datos
            

            
        
        buscar();
        if(ordentx.getText().length()==0){
            JOptionPane.showMessageDialog(this, "no se encontro resultados");
        }
        
    }//GEN-LAST:event_buscarbtActionPerformed

    private void borrarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbtActionPerformed
         if(JOptionPane.showOptionDialog(this, "¿Esta seguro de eliminar la informacion?", "Esta seguro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{" SI "," NO "},"NO")==0)
{
//        JOptionPane.showMessageDialog(this, "La respuesta fue - SI");
      String sql = "delete from cerocontaminacion where calle = ?";
        try{    
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, calletx.getText());
        pst.execute();
        exito();
        borrar();
        }catch (Exception e) {
        System.out.print(e.getMessage());
}
        
    }else{
             
         }
    }//GEN-LAST:event_borrarbtActionPerformed

    private void editarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarbtActionPerformed
       String e =editarbt.getText();
        if (e == "Editar")
        {
        if(JOptionPane.showOptionDialog(this, "¿Esta seguro de editar la informacion?", "Esta seguro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{" SI "," NO "},"NO")==0)
{
//        JOptionPane.showMessageDialog(this, "La respuesta fue - SI");
    editar(true);
    esconderbta();
    borrarbtn.hide();
    editarbt.setText("Actualizar");
    cancelarbt.show();
}
    

else
{
//       JOptionPane.showMessageDialog(this, "La respuesta fue - NO");
}
        }
        if(e=="Actualizar"){
        //base de datos
            //update
            editarbt.setText("Editar");
            mostrarbta();
            borrarbtn.show();
            editar(false);
            
             String sql = "UPDATE `cerocontaminacion` SET atendido='"+atendidotx.getText()+"',calle='"+calletx.getText()+"',colonia='"+coloniatx.getText()+"',cruza='"+cruzatx.getText()+"',trabajo='"+trabajotx.getText()+"',equipo='"+equipotx.getText()+"',fecha='"+fechatx.getDate().toString()+"',municipio='"+municipiotx.getText()+"',nombre='"+nombretx.getText()+"',orden='"+ordentx.getText()+"',tel='"+teltx.getText()+"' WHERE orden =?";
        try{    
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, ordentx.getText());
        pst.execute();
        exito();
        }catch (Exception a) {
            noexito();
                
        System.out.print(a.getMessage());
    }
            
        }
        
    }//GEN-LAST:event_editarbtActionPerformed

    private void editar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_editar
        editar(false);
        cancelarbt.hide();
        caller.setSelected(true);
        
        
    }//GEN-LAST:event_editar

    private void nuevobtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevobtActionPerformed
       String n =nuevobt.getText();
        if (n == "Nuevo")
        {
            nuevobt.setText("Agregar");
            borrar();
            esconderbtn();
            editar(true);
            
        }
        
        if(n=="Agregar"){
        //base de datos
            if(JOptionPane.showOptionDialog(this, "¿Esta seguro de agregar nueva informacion?", "Esta seguro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{" SI "," NO "},"NO")==0)
{
//        JOptionPane.showMessageDialog(this, "La respuesta fue - SI");
//    editar(true);
   //llenado aqui
    if ((equipotx.getText().length()==0)||(fechatx.getDate().toString().length()==0)||(ordentx.getText().length()==0)|| (calletx.getText().length()==0)|| (teltx.getText().length()==0)|| (cruzatx.getText().length()==0)|| (coloniatx.getText().length()==0)|| (municipiotx.getText().length()==0)|| (trabajotx.getText().length()==0)|| (atendidotx.getText().length()==0)){
    JOptionPane.showMessageDialog(this, "falta llenar campos");
    }
    else{
         insertar();
          nuevobt.setText("Nuevo");
            mostrarbtn();
            editar(false);
    }
   
    
//    
    
//    Conectate c = new Conectate();
//    insertar(); 
    
    
}
    

else
{
//       JOptionPane.showMessageDialog(this, "La respuesta fue - NO");
}
//            insertar();
//            nuevobt.setText("Nuevo");
//            mostrarbtn();
//            editar(false);
            
        }
        
    }//GEN-LAST:event_nuevobtActionPerformed

    private void cancelarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarbtActionPerformed
        cancelarbt.hide();
        mostrarbta();
        borrarbtn.show();
        editarbt.show();
        editar(false);
        nuevobt.setText("Nuevo");
        editarbt.setText("Editar");
        
    }//GEN-LAST:event_cancelarbtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        conectar cc= new conectar();
Connection cn= cc.conexion();
    
    if(cn==null)
    {   
        JOptionPane.showMessageDialog(null, "No conectado");
    }
    else
    {
        JOptionPane.showMessageDialog(null, "conectado");
        insertar();
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void calletxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calletxActionPerformed
        
    }//GEN-LAST:event_calletxActionPerformed

    private void borrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbtnActionPerformed
        borrar();
    }//GEN-LAST:event_borrarbtnActionPerformed

    public void esconderbta(){
        buscarbt.hide();
        borrarbt.hide();
        nuevobt.hide();
        
    }
    public void mostrarbta(){
        buscarbt.show();
        borrarbt.show();
        nuevobt.show();
        cancelarbt.hide();
    }
    public void esconderbtn(){
        buscarbt.hide();
        borrarbt.hide();
        editarbt.hide();
        cancelarbt.show();
        borrarbtn.hide();
        
    }
    public void mostrarbtn(){
        buscarbt.show();
        borrarbt.show();
        borrarbtn.show();
        editarbt.show();
        cancelarbt.hide();
    }
    public void editar(Boolean accion){
        ordentx.enable(accion);
        fechatx.enable(accion);
            equipotx.enable(accion);
//            nombretx.enable(accion);
            teltx.enable(accion);
//            calletx.enable(accion);
            cruzatx.enable(accion);
            coloniatx.enable(accion);
            municipiotx.enable(accion);
            trabajotx.enable(accion);
            atendidotx.enable(accion);
            
    }
    public void borrar(){
            ordentx.setText("");
            fechatx.setDate(null);
            equipotx.setText("");
            nombretx.setText("");
            teltx.setText("");
            calletx.setText("");
            cruzatx.setText("");
            coloniatx.setText("");
            municipiotx.setText("");
            trabajotx.setText("");
            atendidotx.setText("");
    }
    
    void insertar(){
        int orden=0;
        try {
        
        PreparedStatement pst = cn.prepareStatement("INSERT INTO cerocontaminacion(atendido,calle,colonia,cruza,trabajo,equipo,fecha,municipio,nombre,orden,tel) VALUES (?,?,?,?,?,?,?,?,?,?,?)");
//        PreparedStatement pst = cn.prepareStatement("INSERT INTO cerocontaminacion(atendido,calle,c) VALUES (?,?,?)");
        pst.setString(10, ordentx.getText());
        pst.setString(7, fechatx.getDate().toString());
        pst.setString(6, equipotx.getText());
        pst.setString(9, nombretx.getText());
        pst.setString(11, teltx.getText());
        pst.setString(2, calletx.getText());
        pst.setString(4, cruzatx.getText());
        pst.setString(3, coloniatx.getText());
        pst.setString(8, municipiotx.getText());
        pst.setString(5, trabajotx.getText());
        pst.setString(1, atendidotx.getText());
        
        
      
        pst.executeUpdate();
//        mostrardatos("");
        exito();
    } catch (Exception e) {
        noexito();
        System.out.print(e.getMessage());
    }
    }
    
    void buscar(){
    String sql="";
    
   
    
//        sql="SELECT * FROM cerocontaminacion WHERE nombre='"+nombretx.getText()+"'";
//        if(JOptionPane.showOptionDialog(this, "¿Esta seguro de agregar nueva informacion?", "Esta seguro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{" Por nombre","Por direccion"},"NO")==0){
//sql="SELECT * FROM cerocontaminacion WHERE nombre='"+nombretx.getText()+"'";
//}

//else{
//    sql="SELECT * FROM cerocontaminacion WHERE calle='"+calletx.getText()+"'";
//       JOptionPane.showMessageDialog(this, "La respuesta fue - NO");
//}
    if(nombrer.isSelected()){
        sql="SELECT * FROM cerocontaminacion WHERE nombre='"+nombretx.getText()+"'";
    }    
    if(caller.isSelected()){
        sql="SELECT * FROM cerocontaminacion WHERE calle='"+calletx.getText()+"'";
    }
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                atendidotx.setText(rs.getString(1));
                calletx.setText(rs.getString(2));
                coloniatx.setText(rs.getString(3));
                cruzatx.setText(rs.getString(4));
                trabajotx.setText(rs.getString(5));
                equipotx.setText(rs.getString(6));
                fechatx.getEditor().setText(rs.getString(7));
//                .getDate().toString()
                municipiotx.setText(rs.getString(8));
                nombretx.setText(rs.getString(9));
                ordentx.setText(rs.getString(10));
                teltx.setText(rs.getString(11));
                }
//            exito();
        } catch (SQLException ex) {
            noexito() ;
            Logger.getLogger(ingresoproductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    void eliminar(){
        
        
        String sql = "delete from cerocontaminacion where calle = ?";
        try{    
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, calletx.getText());
        pst.execute();
        exito();
        }catch (Exception e) {
            noexito();
        System.out.print(e.getMessage());
    }
    }
    
    void exito(){
        JOptionPane.showMessageDialog(this, "La operacion se realizo con exito");
    }
    
    void noexito(){
        JOptionPane.showMessageDialog(this, "La operacion ha sido fallida");
    }
    
    void llenado(){
       
    if ((equipotx.getText().length()==0)|| (calletx.getText().length()==0)|| (teltx.getText().length()==0)|| (cruzatx.getText().length()==0)|| (coloniatx.getText().length()==0)|| (municipiotx.getText().length()==0)|| (trabajotx.getText().length()==0)|| (atendidotx.getText().length()==0)){
    JOptionPane.showMessageDialog(this, "falta llenar campos");
    }
    else{
   
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VISUAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VISUAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VISUAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VISUAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VISUAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Buscarr;
    private javax.swing.JLabel FECHA;
    private javax.swing.JTextField atendidotx;
    private javax.swing.JButton borrarbt;
    private javax.swing.JButton borrarbtn;
    private javax.swing.JButton buscarbt;
    private javax.swing.JRadioButton caller;
    private javax.swing.JTextField calletx;
    private javax.swing.JButton cancelarbt;
    private javax.swing.JTextField coloniatx;
    private javax.swing.JTextField cruzatx;
    private javax.swing.JButton editarbt;
    private javax.swing.JTextField equipotx;
    private org.jdesktop.swingx.JXDatePicker fechatx;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField municipiotx;
    private javax.swing.JRadioButton nombrer;
    private javax.swing.JTextField nombretx;
    private javax.swing.JButton nuevobt;
    private javax.swing.JLabel ordenlbl;
    private javax.swing.JTextField ordentx;
    private javax.swing.JTextField teltx;
    private javax.swing.JTextPane trabajotx;
    // End of variables declaration//GEN-END:variables
conectar cc= new conectar();
    Connection cn= cc.conexion();
    
}
