/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package clases;
import java.awt.Desktop;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juancho
 */
public class VISUAL extends javax.swing.JFrame {
    public String his,his2,his3,his4,his5,calle="";
    String hist[];
    int c;
    Date d,dv;
    DefaultTableModel modelo= new DefaultTableModel();
    String h;
    public VISUAL() {
        initComponents();
        Buscarr.add(nombrer);
        Buscarr.add(caller);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buscarr = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        nombrelbl = new javax.swing.JLabel();
        tellb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        equipolbl = new javax.swing.JLabel();
        fechalbl = new javax.swing.JLabel();
        ordenlbl = new javax.swing.JLabel();
        callelb = new javax.swing.JLabel();
        colonialb = new javax.swing.JLabel();
        cruzalb = new javax.swing.JLabel();
        municipiolb = new javax.swing.JLabel();
        ordentx = new javax.swing.JTextField();
        nombretx = new javax.swing.JTextField();
        equipotx = new javax.swing.JTextField();
        calletx = new javax.swing.JTextField();
        cruzatx = new javax.swing.JTextField();
        coloniatx = new javax.swing.JTextField();
        municipiotx = new javax.swing.JTextField();
        teltx = new javax.swing.JTextField();
        buscarbt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        borrarbt = new javax.swing.JButton();
        editarbt = new javax.swing.JButton();
        nuevobt = new javax.swing.JButton();
        cancelarbt = new javax.swing.JButton();
        nombrer = new javax.swing.JRadioButton();
        caller = new javax.swing.JRadioButton();
        borrarbtn = new javax.swing.JButton();
        apellidoplbl = new javax.swing.JLabel();
        apellidomlbl = new javax.swing.JLabel();
        apellidoptx = new javax.swing.JTextField();
        apellidomtx = new javax.swing.JTextField();
        fechatx = new com.lavantech.gui.comp.DateTimePicker();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        fechavtx = new com.lavantech.gui.comp.DateTimePicker();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tipotx = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nombrevtx = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        trabajotx = new javax.swing.JTextPane();
        jLabel22 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        atendidotx = new javax.swing.JTextField();
        fechavmtx = new javax.swing.JTextField();
        Visita = new javax.swing.JLabel();
        hisbt = new javax.swing.JButton();
        impbt = new javax.swing.JButton();
        fechamtx = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fechav2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nombrelb = new javax.swing.JLabel();
        nombrev2 = new javax.swing.JTextField();
        ultimolb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ultimov2 = new javax.swing.JTextArea();
        atendiolb = new javax.swing.JLabel();
        atendiov2 = new javax.swing.JTextField();
        tipolb = new javax.swing.JLabel();
        fechadv2 = new com.lavantech.gui.comp.DateTimePicker();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbproductos = new javax.swing.JTable();
        hislb = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tipov2 = new javax.swing.JTextArea();
        tel3 = new javax.swing.JTextField();
        tel2 = new javax.swing.JTextField();
        guardarbt = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 894));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                editar(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombrelbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nombrelbl.setText("Nombre(s):");
        getContentPane().add(nombrelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 134, -1, -1));

        tellb.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        tellb.setText("Tel:");
        getContentPane().add(tellb, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 205, -1, -1));

        jLabel3.setText("jLabel1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 82, -1, 0));

        equipolbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        equipolbl.setText("Equipo:");
        getContentPane().add(equipolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 96, -1, -1));

        fechalbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        fechalbl.setText("Fecha y Hora:");
        getContentPane().add(fechalbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 94, -1, -1));

        ordenlbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ordenlbl.setText("Orden de visita:");
        getContentPane().add(ordenlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 94, -1, -1));

        callelb.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        callelb.setText("Calle y nº:");
        getContentPane().add(callelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 172, -1, -1));

        colonialb.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        colonialb.setText("Colonia:");
        getContentPane().add(colonialb, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 205, -1, -1));

        cruzalb.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cruzalb.setText("Cruza con:");
        getContentPane().add(cruzalb, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 172, -1, -1));

        municipiolb.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        municipiolb.setText("Municipio:");
        getContentPane().add(municipiolb, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 205, -1, -1));

        ordentx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(ordentx, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 89, 130, -1));

        nombretx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nombretx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretxActionPerformed(evt);
            }
        });
        getContentPane().add(nombretx, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 129, 350, -1));

        equipotx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(equipotx, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 91, 450, -1));

        calletx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        calletx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calletxActionPerformed(evt);
            }
        });
        getContentPane().add(calletx, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 167, 362, -1));

        cruzatx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(cruzatx, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 167, 186, -1));

        coloniatx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(coloniatx, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 199, 293, -1));

        municipiotx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(municipiotx, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 199, 160, -1));

        teltx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(teltx, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 199, 160, -1));

        buscarbt.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        buscarbt.setText("Buscar");
        buscarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbtActionPerformed(evt);
            }
        });
        getContentPane().add(buscarbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 592, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 60)); // NOI18N
        jLabel13.setText("CEROCONTAMINACION");

        jLabel5.setText("CHEQUEO DE CALENTADOR SOLAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(384, 384, 384))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 76));

        borrarbt.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        borrarbt.setText("Eliminar");
        borrarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbtActionPerformed(evt);
            }
        });
        getContentPane().add(borrarbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 630, -1, -1));

        editarbt.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        editarbt.setText("Editar");
        editarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarbtActionPerformed(evt);
            }
        });
        getContentPane().add(editarbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 592, -1, -1));

        nuevobt.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nuevobt.setText("Nuevo");
        nuevobt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevobtActionPerformed(evt);
            }
        });
        getContentPane().add(nuevobt, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 592, -1, -1));

        cancelarbt.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        cancelarbt.setText("Cancelar");
        cancelarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarbtActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 592, -1, -1));

        nombrer.setText("Apellido");
        nombrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrerActionPerformed(evt);
            }
        });
        getContentPane().add(nombrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 632, -1, -1));

        caller.setText("Calle");
        caller.setAutoscrolls(true);
        caller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callerActionPerformed(evt);
            }
        });
        getContentPane().add(caller, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 652, -1, -1));

        borrarbtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        borrarbtn.setText("Borrar");
        borrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbtnActionPerformed(evt);
            }
        });
        getContentPane().add(borrarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 592, -1, -1));

        apellidoplbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        apellidoplbl.setText("Apellido paterno:");
        getContentPane().add(apellidoplbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 134, -1, -1));

        apellidomlbl.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        apellidomlbl.setText("Apellido materno:");
        getContentPane().add(apellidomlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 134, -1, -1));

        apellidoptx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(apellidoptx, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 129, 170, -1));

        apellidomtx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(apellidomtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 129, 173, -1));
        getContentPane().add(fechatx, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 93, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel17.setText("Fecha y Hora:");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(7, 7, 118, 22);
        jPanel3.add(fechavtx);
        fechavtx.setBounds(137, 7, 152, 28);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel18.setText("Atendio");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(307, 12, 67, 22);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel19.setText("Tipo de falla");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(596, 12, 108, 22);

        tipotx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jPanel3.add(tipotx);
        tipotx.setBounds(716, 7, 204, 32);

        jLabel20.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel20.setText("Cliente satisfecho:");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(7, 45, 160, 22);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel21.setText("Nombre");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(7, 82, 69, 22);

        nombrevtx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jPanel3.add(nombrevtx);
        nombrevtx.setBounds(82, 77, 228, 32);

        trabajotx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(trabajotx);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(19, 143, 921, 287);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel22.setText("Ultimo realizado");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(13, 115, 142, 22);

        jButton3.setText("Imprimir");
        jPanel3.add(jButton3);
        jButton3.setBounds(7, 436, 98, 29);

        atendidotx.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jPanel3.add(atendidotx);
        atendidotx.setBounds(380, 7, 150, 32);

        fechavmtx.setText("jTextField1");
        fechavmtx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechavmtxActionPerformed(evt);
            }
        });
        jPanel3.add(fechavmtx);
        fechavmtx.setBounds(140, 10, 150, 26);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 265, 0, 0));

        Visita.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Visita.setText("Visita:");
        getContentPane().add(Visita, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 237, -1, -1));

        hisbt.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        hisbt.setText("Historial completo");
        hisbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hisbtActionPerformed(evt);
            }
        });
        getContentPane().add(hisbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 630, -1, -1));

        impbt.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        impbt.setText("Imprimir");
        impbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impbtActionPerformed(evt);
            }
        });
        getContentPane().add(impbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, -1, -1));
        getContentPane().add(fechamtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 96, 150, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("Fecha y hora:");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText("Cliente satisfecho:");

        nombrelb.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nombrelb.setText("Nombre:");

        nombrev2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        ultimolb.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ultimolb.setText("Ultimo realizado:");

        ultimov2.setColumns(20);
        ultimov2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ultimov2.setRows(5);
        jScrollPane1.setViewportView(ultimov2);

        atendiolb.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        atendiolb.setText("Atendio:");

        atendiov2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        tipolb.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        tipolb.setText("Tipo de falla:");

        tbproductos.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        tbproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "trabajo", "fecha"
            }
        ));
        jScrollPane3.setViewportView(tbproductos);

        hislb.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        hislb.setText("Historial completo:");

        tipov2.setColumns(20);
        tipov2.setRows(5);
        jScrollPane4.setViewportView(tipov2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ultimolb)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hislb)
                                .addGap(141, 141, 141)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombrelb)
                                .addGap(1, 1, 1)
                                .addComponent(nombrev2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(12, 12, 12)
                                .addComponent(fechadv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechav2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(atendiolb)
                                .addGap(22, 22, 22)))
                        .addGap(11, 11, 11)
                        .addComponent(atendiov2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tipolb)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(fechav2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(atendiolb)
                                .addComponent(atendiov2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tipolb))
                            .addComponent(fechadv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(nombrelb)
                            .addComponent(nombrev2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ultimolb)
                            .addComponent(hislb)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 271, 1110, -1));

        tel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(tel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, 150, -1));

        tel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        getContentPane().add(tel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 160, -1));

        guardarbt.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        guardarbt.setText("Guardar");
        guardarbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarbtActionPerformed(evt);
            }
        });
        getContentPane().add(guardarbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 630, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombretxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretxActionPerformed
       
    }//GEN-LAST:event_nombretxActionPerformed

    private void buscarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbtActionPerformed
   
//    JOptionPane.showMessageDialog(this, "falta llenar campos");
    
        //base de datos
            

        guardarbt.setVisible(true);
        impbt.setVisible(true);
        hisbt.setVisible(true);
        buscar();
//        historialt();
        
        fechatx.show(false);
        fechamtx.show(true);
        fechavmtx.show(true);
        fechav2.show(true);
        fechadv2.show(false);
        if(ordentx.getText().length()==0){
            JOptionPane.showMessageDialog(this, "no se encontro resultados");
        }
        
    }//GEN-LAST:event_buscarbtActionPerformed

    private void borrarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbtActionPerformed
         if(JOptionPane.showOptionDialog(this, "¿Esta seguro de eliminar la informacion?", "Esta seguro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{" SI "," NO "},"NO")==0)
{
//        JOptionPane.showMessageDialog(this, "La respuesta fue - SI");
      String sql = "delete from cerocontaminacion where calle = ?";
        try{    
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, calletx.getText());
        pst.execute();
//        exito();
        
        }catch (Exception e) {
        System.out.print(e.getMessage());
}
       eliminar(); borrar();
    }else{
             
         }
    }//GEN-LAST:event_borrarbtActionPerformed

    private void editarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarbtActionPerformed
        
        hisbt.hide();
        impbt.hide();
        if((equipotx.getText().length()==0)){JOptionPane.showMessageDialog(this, "tiene que hacer una busqueda");}
       else{
           fechamtx.show(false);
            fechav2.show(false);
            fechatx.show(true);
            fechadv2.show(true);
            
        String e =editarbt.getText();
        if (e == "Editar")
        {
        if(JOptionPane.showOptionDialog(this, "¿Esta seguro de editar la informacion?", "Esta seguro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{" SI "," NO "},"NO")==0)
{
//        JOptionPane.showMessageDialog(this, "La respuesta fue - SI");
    nombrev2.setText("");
    atendiov2.setText("");
    tipov2.setText("");
    editar(true);
    esconderbta();
    borrarbtn.hide();
    editarbt.setText("Actualizar");
    cancelarbt.show();
    ultimov2.setText("");
    
}
    

else
{
//       JOptionPane.showMessageDialog(this, "La respuesta fue - NO");
}
        }
        if(e=="Actualizar"){
        //base de datos
            actualizar();
            
        }
       }
    }//GEN-LAST:event_editarbtActionPerformed

    private void editar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_editar
        editar(false);
        cancelarbt.hide();
        caller.setSelected(true);
        fechamtx.show(false);
        fechavmtx.show(false);
        fechav2.show(false);
        ordentx.enable(false);
//        apellidoptx.enable(false);
        hisbt.hide();
        impbt.hide();
        guardarbt.hide();
       modelo.addColumn("Historial");
    modelo.addColumn("Fecha");
    modelo.addColumn("Falla");
    modelo.addColumn("Atendio");
    modelo.addColumn("Nombre");
    tbproductos.setModel(modelo);
        
       
        
    }//GEN-LAST:event_editar

    private void nuevobtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevobtActionPerformed
       String n =nuevobt.getText();
       hisbt.hide();
        impbt.hide();
        if (n == "Nuevo")
        {
            nuevobt.setText("Agregar");
            apellidoptx.enable(true);
            borrar();
            sumar();
            esconderbtn();
            fechatx.show(true);
            fechadv2.show(true);
        fechamtx.show(false);
        fechavmtx.show(false);
        fechav2.show(false);
            editar(true);
            ordentx.enable(false);
            
        }
        
        if(n=="Agregar"){
        //base de datos
            if(JOptionPane.showOptionDialog(this, "¿Esta seguro de agregar nueva informacion?", "Esta seguro", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{" SI "," NO "},"NO")==0)
{
//        JOptionPane.showMessageDialog(this, "La respuesta fue - SI");
//    editar(true);
   //llenado aqui
    if ((equipotx.getText().length()==0)|| (calletx.getText().length()==0)|| (teltx.getText().length()==0)|| (cruzatx.getText().length()==0)|| (coloniatx.getText().length()==0)|| (municipiotx.getText().length()==0)||  (tipov2.getText().length()==0)||  (apellidomtx.getText().length()==0)||  (apellidoptx.getText().length()==0)||  (nombretx.getText().length()==0)){
    JOptionPane.showMessageDialog(this, "falta llenar campos");
    }
    else{
        buscara();
//         insertar();
//         sumarh();
         historial();
          nuevobt.setText("Nuevo");
            mostrarbtn();
            editar(false);
    }
   
    
//    
    
//    Conectate c = new Conectate();
//    insertar(); 
    
    
}
    

else
{
//       JOptionPane.showMessageDialog(this, "La respuesta fue - NO");
}
//            insertar();
//            nuevobt.setText("Nuevo");
//            mostrarbtn();
//            editar(false);
            
        }
        
    }//GEN-LAST:event_nuevobtActionPerformed

    private void cancelarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarbtActionPerformed
        cancelarbt.hide();
        mostrarbta();
        borrarbtn.show();
        editarbt.show();
        editar(false);
        nuevobt.setText("Nuevo");
        editarbt.setText("Editar");
        borrar();
        hisbt.hide();
        impbt.hide();
    }//GEN-LAST:event_cancelarbtActionPerformed

    private void calletxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calletxActionPerformed
        
    }//GEN-LAST:event_calletxActionPerformed

    private void borrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbtnActionPerformed
      
        borrar();
    }//GEN-LAST:event_borrarbtnActionPerformed

    private void fechavmtxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechavmtxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechavmtxActionPerformed

    private void nombrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrerActionPerformed
            // TODO add your handling code here:
//        apellidoptx.enable(true);
//        calletx.enable(false);
    }//GEN-LAST:event_nombrerActionPerformed

    private void callerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callerActionPerformed
        // TODO add your handling code here:
//        apellidoptx.enable(false);
//        calletx.enable(true);
    }//GEN-LAST:event_callerActionPerformed

    private void hisbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hisbtActionPerformed
    hisbt.show(false);
        String sql="";
    sql="SELECT * FROM `visita` WHERE orden ='"+ordentx.getText()+"' ";
    
    String []datos = new String [5];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                datos[0]=rs.getString(3);
                
                datos[1]=rs.getString(4);
                datos[2]=rs.getString(6);
                datos[3]=rs.getString(5);
                datos[4]=rs.getString(7);
                modelo.addRow(datos);
            }
//            his=datos[0];
            c=modelo.getRowCount();
            for (int i = 0; i < modelo.getRowCount(); i++) {
//                int o=0;
//                System.out.println(his[i]);
//            his = (String.valueOf(tbproductos.getValueAt(i,0)));
//            System.out.println(his);
//            hist[0]=his;
//            o++;
            tbproductos.setModel(modelo);}
        } catch (SQLException ex) {
            Logger.getLogger(ingresoproductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_hisbtActionPerformed

    private void impbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impbtActionPerformed
        // TODO add your handling code here:
        archivo();
        try {
            imprimir();
        } catch (IOException ex) {
            Logger.getLogger(VISUAL.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_impbtActionPerformed

    private void guardarbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarbtActionPerformed
        // TODO add your handling code here:
        archivo();
    }//GEN-LAST:event_guardarbtActionPerformed

    public void esconderbta(){
        buscarbt.hide();
        borrarbt.hide();
        nuevobt.hide();
        
    }
    public void mostrarbta(){
        buscarbt.show();
        borrarbt.show();
        nuevobt.show();
        cancelarbt.hide();
    }
    public void esconderbtn(){
        buscarbt.hide();
        borrarbt.hide();
        editarbt.hide();
        cancelarbt.show();
        borrarbtn.hide();
        
    }
    public void mostrarbtn(){
        buscarbt.show();
        borrarbt.show();
        borrarbtn.show();
        editarbt.show();
        cancelarbt.hide();
    }
    public void editar(Boolean accion){
        guardarbt.enable(accion);
        ordentx.enable(accion);
        fechatx.enable(accion);
        fechav2.enable(accion);
            equipotx.enable(accion);
            nombretx.enable(accion);
            teltx.enable(accion);
//            calletx.enable(accion);
            cruzatx.enable(accion);
            coloniatx.enable(accion);
            municipiotx.enable(accion);
            trabajotx.enable(accion);
            atendidotx.enable(accion);
//            apellidoptx.enable(accion);
            apellidomtx.enable(accion);
            tipotx.enable(accion);
            nombrevtx.enable(accion);
            fechamtx.enable(accion);
            fechadv2.enable(accion);
            tipov2.enable(accion);
            nombrev2.enable(accion);
            ultimov2.enable(accion);
            atendiov2.enable(accion);
            tel2.enable(accion);
            tel3.enable(accion);
            
    
    }
    
    void archivo() {
        File f;
f = new File("/reportes/"+calletx.getText()+".txt");

//Escritura
try{
FileWriter w = new FileWriter(f);
BufferedWriter bw = new BufferedWriter(w);
PrintWriter wr = new PrintWriter(bw);	
wr.write("                       CEROCONTAMINACION");
wr.write("\n");
wr.write(ordenlbl.getText() +""+ordentx.getText()+" "+fechalbl.getText()+fechamtx.getText()+" "+equipolbl.getText()+equipotx.getText()+ "\n");
wr.write(apellidoplbl.getText()+apellidoptx.getText()+" "+apellidomlbl.getText()+apellidomtx.getText()+" "+nombrelbl.getText()+nombretx.getText()+"\n");
wr.write(callelb.getText()+calletx.getText()+" "+cruzalb.getText()+cruzatx.getText()+"\n");
wr.write(colonialb.getText()+coloniatx.getText()+" "+municipiolb.getText()+municipiotx.getText()+" "+tellb.getText()+teltx.getText()+"  "+tel2.getText()+"  "+tel3.getText()+"\n");
wr.write("Visita:");
wr.write("\n");
wr.write(fechalbl.getText()+fechav2.getText()+" "+atendiolb.getText()+atendiov2.getText()+" "+tipolb.getText()+tipov2.getText()+"\n");
wr.write(apellidoplbl.getText()+apellidoptx.getText()+" "+apellidomlbl.getText()+apellidomtx.getText()+" "+nombrelbl.getText()+nombretx.getText()+"\n");
wr.write("Cliente satisfecho:");
wr.write("\n");
wr.write(nombrelb.getText()+nombrev2.getText()+"\n");
wr.write(ultimolb.getText()+"\n");
wr.write(ultimov2.getText()+"\n");
wr.write(ultimov2.getText()+"Historial\n");
for (int i = 0; i < modelo.getRowCount(); i++) {
            
            his = (String.valueOf(tbproductos.getValueAt(i,0)));
            his2 = (String.valueOf(tbproductos.getValueAt(i,1)));
            his3 = (String.valueOf(tbproductos.getValueAt(i,2)));
            his4 = (String.valueOf(tbproductos.getValueAt(i,3)));
            his5 = (String.valueOf(tbproductos.getValueAt(i,4)));
            System.out.println(his+his2+his3+his4+his5);
            wr.write(his+" "+his2+" "+his3+" "+his4 +" "+his5+"\n");
           }
wr.close();
bw.close();
JOptionPane.showMessageDialog(null, "archivo guardado en reportes");
}catch(IOException e){};
       
    }
    
    void imprimir() throws IOException{
   
		File fileToPrint = new File("/reportes/"+calletx.getText()+".txt");
		Desktop.getDesktop().print(fileToPrint);
    }
    
    public void borrar(){
       hisbt.hide();
        impbt.hide();
            ordentx.setText("");
//            fechatx.setDate(null);
            equipotx.setText("");
            apellidoptx.setText("");
            apellidomtx.setText("");
            nombretx.setText("");
            teltx.setText("");
            calletx.setText("");
            cruzatx.setText("");
            coloniatx.setText("");
            municipiotx.setText("");
            trabajotx.setText("");
            atendidotx.setText("");
            tipotx.setText("");
            nombrevtx.setText("");
//            fechavtx.setDate(null);    
            tipov2.setText("");
            atendiov2.setText("");
            nombrev2.setText("");
            ultimov2.setText("");
            String []d = new String [5];
            clrtabla();
            
           
    }
    
    private void clrtabla(){
       for (int i = 0; i < modelo.getRowCount(); i++) {
           modelo.removeRow(i);
           i-=1;
       }
   }
    void insertar(){
        int orden=0;
        try {
        
        PreparedStatement pst = cn.prepareStatement("INSERT INTO cerocontaminacion(atendido,calle,colonia,cruza,trabajo,equipo,fecha,municipio,apellidop,apellidom,nombre,orden,tel,fechav,tipo,nombrev,tel2,tel3) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
//        PreparedStatement pst = cn.prepareStatement("INSERT INTO cerocontaminacion(atendido,calle,c) VALUES (?,?,?)");
        pst.setString(12, ordentx.getText());
        //obtener fecha
        d = fechatx.getDate();
        
        //convertir a cadena
        DateFormat dateFormat = new SimpleDateFormat("d/MM/yy H:mm");
        String strDate = dateFormat.format(d);
        pst.setString(7, strDate);
        pst.setString(6, equipotx.getText());
        pst.setString(11, nombretx.getText());
        pst.setString(13, teltx.getText());
        pst.setString(2, calletx.getText());
        pst.setString(4, cruzatx.getText());
        pst.setString(3, coloniatx.getText());
        pst.setString(8, municipiotx.getText());
        pst.setString(5, ultimov2.getText());
        pst.setString(1, atendiov2.getText());
        pst.setString(9, apellidoptx.getText());
        pst.setString(10, apellidomtx.getText());
        //obtener fecha
        dv = fechadv2.getDate();
        
        //convertir a cadena
        String strDate2 = dateFormat.format(dv);
        pst.setString(14, strDate2);
//        pst.setString(1, fechavtx.getDate().toString());
        
        pst.setString(15, tipov2.getText());
        pst.setString(16, nombrev2.getText());
        pst.setString(17, tel2.getText());
        pst.setString(18, tel3.getText());
        
        
      
        pst.executeUpdate();
//        mostrardatos("");
//        exito();
    } catch (Exception e) {
        noexito();
        System.out.print(e.getMessage());
    }
        
        //visita
//        try {
//        
//        PreparedStatement pst = cn.prepareStatement("INSERT INTO visita(fechav,tipo,nombrev) VALUES (?,?,?)");
////        PreparedStatement pst = cn.prepareStatement("INSERT INTO cerocontaminacion(atendido,calle,c) VALUES (?,?,?)");
//        dv = fechavtx.getDate();
//        DateFormat dateFormat = new SimpleDateFormat("d/MM/yy H:mm");
//        //convertir a cadena
//        String strDate = dateFormat.format(dv);
//        pst.setString(1, strDate);
////        pst.setString(1, fechavtx.getDate().toString());
//        
//        pst.setString(2, tipotx.getText());
//        pst.setString(3, nombrevtx.getText());
//        
//        
//        
//      
//        pst.executeUpdate();
////        mostrardatos("");
//        exito();
//    } catch (Exception e) {
//        noexito();
//        System.out.print(e.getMessage());
//    }
        
        
    }
    void sumar(){
    String sql="",ns;
    int n;
    
        
        sql="SELECT max(orden)+1 FROM cerocontaminacion";
    
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
//                
                ordentx.setText(rs.getString(1));
                
                }
//            exito();
        } catch (SQLException ex) {
            noexito() ;
            Logger.getLogger(ingresoproductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    void buscar(){
    String sql="";
    
    
    if(nombrer.isSelected()){
         
        sql="SELECT * FROM cerocontaminacion WHERE apellidop='"+apellidoptx.getText()+"'";
    }    
    if(caller.isSelected()){
        
        sql="SELECT * FROM cerocontaminacion WHERE calle='"+calletx.getText()+"'";
    }
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                atendiov2.setText(rs.getString(1));
                calletx.setText(rs.getString(2));
                coloniatx.setText(rs.getString(3));
                cruzatx.setText(rs.getString(4));
                ultimov2.setText(rs.getString(5));
                equipotx.setText(rs.getString(6));
                fechamtx.setText(rs.getString(7));
                municipiotx.setText(rs.getString(8));
                apellidoptx.setText(rs.getString(9));
                apellidomtx.setText(rs.getString(10));
                nombretx.setText(rs.getString(11));
                ordentx.setText(rs.getString(12));
                teltx.setText(rs.getString(13));
                fechav2.setText(rs.getString(14));
                tipov2.setText(rs.getString(15));
                nombrev2.setText(rs.getString(16));
                tel2.setText(rs.getString(17));
                tel3.setText(rs.getString(18));
                }
//            exito();
        } catch (SQLException ex) {
            noexito() ;
            Logger.getLogger(ingresoproductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    void buscara(){
    String sql="";
    
    
    if(nombrer.isSelected()){
         
        sql="SELECT * FROM cerocontaminacion WHERE apellidop='"+apellidoptx.getText()+"'";
    }    
    if(caller.isSelected()){
        
        sql="SELECT * FROM cerocontaminacion WHERE calle='"+calletx.getText()+"'";
    }
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                
                calle =(rs.getString(2));    
                System.out.println(calle);
                
                }
            if(calle.equals(calletx.getText())){
                   System.out.println("actualiza");
                   actualizar();
                   
                }
//            else{System.out.println("no igual");}
//            exito();
        } catch (SQLException ex) {
            noexito() ;
            Logger.getLogger(ingresoproductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(!calle.equals(calletx.getText()))
        {
            insertar();
            
        }
    }
    
//    void buscarv(){
//    String sql="";
//    
//    
//    
//        sql="SELECT * FROM visita WHERE calle='"+calletx.getText()+"'";
//    
//        try {
//            Statement st = cn.createStatement();
//            ResultSet rs = st.executeQuery(sql);
//            while(rs.next()){
//                fechavmtx.setText(rs.getString(1));
//                tipotx.setText(rs.getString(2));
//                nombrevtx.setText(rs.getString(3));
//                
//                }
////            exito();
//        } catch (SQLException ex) {
//            noexito() ;
//            Logger.getLogger(ingresoproductos.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//        
//    }
    
    void historial(){
     try {
        DateFormat dateFormat = new SimpleDateFormat("d/MM/yy H:mm");
        PreparedStatement pst = cn.prepareStatement("INSERT INTO visita(orden,id,trabajo,fecha,atendio,falla,nombre) VALUES (?,?,?,?,?,?,?)");
//        PreparedStatement pst = cn.prepareStatement("INSERT INTO cerocontaminacion(atendido,calle,c) VALUES (?,?,?)");
        pst.setString(1, ordentx.getText());
        pst.setString(2, calletx.getText());
        pst.setString(3,ultimov2.getText());
        dv = fechadv2.getDate();
        
        //convertir a cadena
        String strDate2 = dateFormat.format(dv);
        pst.setString(4, strDate2);
        pst.setString(5,atendiov2.getText());
        pst.setString(6,tipov2.getText());
        pst.setString(7,nombrev2.getText());
        
      
        pst.executeUpdate();
//        mostrardatos("");
//        exito();
    } catch (Exception e) {
        noexito();
        System.out.print(e.getMessage());
    }
    }
    
    void sumarh(){
    String sql="";
   
    
        
        sql="SELECT max(id)+1 FROM visita";
    
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
//              
                h= (rs.getString(1));
                
                }
//            exito();
        } catch (SQLException ex) {
            noexito() ;
            Logger.getLogger(ingresoproductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void actualizar(){
    //update
            editarbt.setText("Editar");
            mostrarbta();
            borrarbtn.show();
            
            editar(false);
            //obtener fecha
        d = fechatx.getDate();
        
        //convertir a cadena
        DateFormat dateFormat = new SimpleDateFormat("d/MM/yy H:mm");
        String strDate = dateFormat.format(d);
        //obtener fecha
        dv = fechadv2.getDate();
        
        //convertir a cadena
        
        String strDatev = dateFormat.format(dv);
        System.out.println(strDatev);
             String sql = "UPDATE `cerocontaminacion` SET atendido='"+atendiov2.getText()+"',calle='"+calletx.getText()+"',colonia='"+coloniatx.getText()+"',cruza='"+cruzatx.getText()+"',trabajo='"+ultimov2.getText()+"',equipo='"+equipotx.getText()+"',fecha='"+strDate+"',municipio='"+municipiotx.getText()+"',apellidop='"+apellidoptx.getText()+"',apellidom='"+apellidomtx.getText()+"',nombre='"+nombretx.getText()+"',orden='"+ordentx.getText()+"',tel='"+teltx.getText()+"',fechav='"+strDatev+"',tipo='"+tipov2.getText()+"',nombrev='"+nombrev2.getText()+"',tel2='"+tel2.getText()+"',tel3='"+tel3.getText()+"' WHERE calle =?";
        try{    
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, calletx.getText());
        pst.execute();
        exito();
        }catch (Exception a) {
            noexito();
                
        System.out.print(a.getMessage());
    }
//        sumarh();
        historial();
        hisbt.show(true);
    impbt.show(true);
    }
    
    void eliminar(){
        
        
        String sql = "delete from visita where orden = ?";
        try{    
        PreparedStatement pst = cn.prepareStatement(sql);
        pst.setString(1, ordentx.getText());
        pst.execute();
        exito();
        }catch (Exception e) {
            noexito();
        System.out.print(e.getMessage());
    }
    }
    
    void exito(){
        JOptionPane.showMessageDialog(this, "La operacion se realizo con exito");
    }
    
    void noexito(){
        JOptionPane.showMessageDialog(this, "La operacion ha sido fallida");
    }
    
    void llenado(){
       
    if ((equipotx.getText().length()==0)|| (calletx.getText().length()==0)|| (teltx.getText().length()==0)|| (cruzatx.getText().length()==0)|| (coloniatx.getText().length()==0)|| (municipiotx.getText().length()==0)|| (ultimov2.getText().length()==0)|| (atendiov2.getText().length()==0)|| (nombrev2.getText().length()==0)|| (tipov2.getText().length()==0)){
    JOptionPane.showMessageDialog(this, "falta llenar campos");
    }
    else{
   
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VISUAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VISUAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VISUAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VISUAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VISUAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Buscarr;
    private javax.swing.JLabel Visita;
    private javax.swing.JLabel apellidomlbl;
    private javax.swing.JTextField apellidomtx;
    private javax.swing.JLabel apellidoplbl;
    private javax.swing.JTextField apellidoptx;
    private javax.swing.JTextField atendidotx;
    private javax.swing.JLabel atendiolb;
    private javax.swing.JTextField atendiov2;
    private javax.swing.JButton borrarbt;
    private javax.swing.JButton borrarbtn;
    private javax.swing.JButton buscarbt;
    private javax.swing.JLabel callelb;
    private javax.swing.JRadioButton caller;
    private javax.swing.JTextField calletx;
    private javax.swing.JButton cancelarbt;
    private javax.swing.JLabel colonialb;
    private javax.swing.JTextField coloniatx;
    private javax.swing.JLabel cruzalb;
    private javax.swing.JTextField cruzatx;
    private javax.swing.JButton editarbt;
    private javax.swing.JLabel equipolbl;
    private javax.swing.JTextField equipotx;
    private com.lavantech.gui.comp.DateTimePicker fechadv2;
    private javax.swing.JLabel fechalbl;
    private javax.swing.JTextField fechamtx;
    private com.lavantech.gui.comp.DateTimePicker fechatx;
    private javax.swing.JTextField fechav2;
    private javax.swing.JTextField fechavmtx;
    private com.lavantech.gui.comp.DateTimePicker fechavtx;
    private javax.swing.JButton guardarbt;
    private javax.swing.JButton hisbt;
    private javax.swing.JLabel hislb;
    private javax.swing.JButton impbt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel municipiolb;
    private javax.swing.JTextField municipiotx;
    private javax.swing.JLabel nombrelb;
    private javax.swing.JLabel nombrelbl;
    private javax.swing.JRadioButton nombrer;
    private javax.swing.JTextField nombretx;
    private javax.swing.JTextField nombrev2;
    private javax.swing.JTextField nombrevtx;
    private javax.swing.JButton nuevobt;
    private javax.swing.JLabel ordenlbl;
    private javax.swing.JTextField ordentx;
    private javax.swing.JTable tbproductos;
    private javax.swing.JTextField tel2;
    private javax.swing.JTextField tel3;
    private javax.swing.JLabel tellb;
    private javax.swing.JTextField teltx;
    private javax.swing.JLabel tipolb;
    private javax.swing.JTextField tipotx;
    private javax.swing.JTextArea tipov2;
    private javax.swing.JTextPane trabajotx;
    private javax.swing.JLabel ultimolb;
    private javax.swing.JTextArea ultimov2;
    // End of variables declaration//GEN-END:variables
conectar cc= new conectar();
    Connection cn= cc.conexion();
    
}
